[package]
name = "ephemeral_echo_circuits"
type = "bin"
authors = ["sym"] 
# noir ver check
compiler_version = "1.0.0"
entry = "src/main.nr"
expression_width = "8" # bigger = slower
backend = "barretenberg"
prove_time = "default"


[dependencies]
# local zk-kit path deps
zk_kit_merkle = { path = "../zk-kit.noir/packages/merkle-trees" }

# jwt lib for noir 1 beta3
noir_jwt = { git = "https://github.com/zkemail/noir-jwt.git", tag = "v0.4.4" }

# std lib already there

# acir stuff
[optimization]
acir_pass_manager = true
inline_cost = 20  # inline threshold
