[package]
name = "ephemeral_echo_circuits"
type = "bin"
authors = ["sym"] # Your name
# IMPORTANT: Match your nargo --version output for noirc
compiler_version = "1.0.0"
entry = "src/main.nr"
expression_width = "8" # or higher values like 12, 18
backend = "barretenberg"
prove_time = "default"


[dependencies]
# Using a local path dependency for zk-kit.
# The main branch of zk-kit.noir should be more compatible with a newer Noir like 1.0.0-beta.3
zk_kit_merkle = { path = "../zk-kit.noir/packages/merkle-trees" }

# Trying noir-jwt v0.4.4 again, as per its README for Noir v1.0.0-beta.3
noir_jwt = { git = "https://github.com/zkemail/noir-jwt.git", tag = "v0.4.4" }

# Standard library is implicitly available and will match your compiler_version.

# If using ACIR optimizer
[optimization]
acir_pass_manager = true
inline_cost = 20  # Threshold for function inlining
